name: build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm ci
    - name: build
      run: npm run make -- --arch=ia32
    - name: debug
      run: find .
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: Release.txt
