name: build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%y%m%d.%H.%M")"
        sed -i "s/\"1.0.0\"/\"$(date +'%y%m%d.%H.%M')\"/" package.json
    - name: install dependencies
      run: npm ci
    - name: build
      run: npm run make -- --arch=ia32
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: "out/make/*/*/*"
        tag_name: ${{ steps.tag.outputs.release_tag }}
