name: build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm ci
    - name: build
      run: npm run make -- --arch=ia32
    - name: generate release tag
      id: tag
      run: echo "::set-output name=release_tag::nightly_$(date +"%Y.%m.%d_%H-%M")"
    - name: debugging
      run: Get-ChildItem -Recurse
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: label-terminal\out\make\squirrel.windows\ia32\label-terminal-1.0.0 Setup.exe
        tag_name: ${{ steps.tag.outputs.release_tag }}
